In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
class MyLinear:
    def __init__(self, input_size, output_size):
        self.input_size = input_size
        self.output_size = output_size

        self.W = np.random.randn(self.input_size, self.output_size)
        self.b = np.random.randn(self.output_size)
        self.x = None

    def forward(self, x):
        self.x = x
        return x @ self.W + self.b

    def backward(self, grad_outp):
        dL_db = grad_outp.sum(axis=0)
        dL_dw = self.x.T @ grad_outp 
        dL_dx = grad_outp @ self.W.T

        return dL_dx

In [18]:
model = MyLinear(2, 3)
model.forward(np.array([1, 2]))

[[ 0.40619194  1.50424345 -0.04760162]
 [ 0.21245425 -0.81535812  1.30632392]] [ 0.38483819  0.98489703 -0.76912097]


array([1.21593863, 0.85842424, 1.79592526])